# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/fakhr/OneDrive/Documents/Vivado/heart-rate-monitor/heart-rate-monitor.srcs/sources_1/new/signal_processor.sv
  C:/Users/fakhr/OneDrive/Documents/Vivado/heart-rate-monitor/heart-rate-monitor.srcs/sources_1/new/display_driver.sv
  C:/Users/fakhr/OneDrive/Documents/Vivado/heart-rate-monitor/heart-rate-monitor.srcs/sources_1/new/bpm_calculator.sv
  C:/Users/fakhr/OneDrive/Documents/Vivado/heart-rate-monitor/heart-rate-monitor.srcs/sources_1/new/adc_interface.sv
  C:/Users/fakhr/OneDrive/Documents/Vivado/heart-rate-monitor/heart-rate-monitor.srcs/sources_1/new/heart_rate_monitor.sv
}
read_xdc C:/Users/fakhr/OneDrive/Documents/Vivado/heart-rate-monitor/heart-rate-monitor.srcs/constrs_1/new/heart_rate_monitor.xdc
set_property used_in_implementation false [get_files C:/Users/fakhr/OneDrive/Documents/Vivado/heart-rate-monitor/heart-rate-monitor.srcs/constrs_1/new/heart_rate_monitor.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/fakhr/OneDrive/Documents/Vivado/heart-rate-monitor/heart-rate-monitor.cache/wt [current_project]
set_property parent.project_dir C:/Users/fakhr/OneDrive/Documents/Vivado/heart-rate-monitor [current_project]
catch { write_hwdef -file heart_rate_monitor.hwdef }
synth_design -top heart_rate_monitor -part xc7a100tcsg324-1
write_checkpoint heart_rate_monitor.dcp
report_utilization -file heart_rate_monitor_utilization_synth.rpt -pb heart_rate_monitor_utilization_synth.pb
